2023-03-09 19:26:19,388 INFO    Thread-17 :26780 [wandb_setup.py:_flush():68] Configure stats pid to 26780
2023-03-09 19:26:19,388 INFO    Thread-17 :26780 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Shivam Maurya\.config\wandb\settings
2023-03-09 19:26:19,388 INFO    Thread-17 :26780 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Shivam Maurya\OneDrive\Desktop\IIT MADRAS\Deep Learning\assignment 1\CS6910-Deep_Learning_Assignment-1\wandb\settings
2023-03-09 19:26:19,388 INFO    Thread-17 :26780 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'project': 'CS6910_Assignment_1', 'entity': 'cs22m083', 'root_dir': 'C:\\Users\\Shivam Maurya\\OneDrive\\Desktop\\IIT MADRAS\\Deep Learning\\assignment 1\\CS6910-Deep_Learning_Assignment-1', 'sweep_id': '6q4mnv2r', 'run_id': 'znk3ejhp', 'sweep_param_path': 'C:\\Users\\Shivam Maurya\\OneDrive\\Desktop\\IIT MADRAS\\Deep Learning\\assignment 1\\CS6910-Deep_Learning_Assignment-1\\wandb\\sweep-6q4mnv2r\\config-znk3ejhp.yaml'}
2023-03-09 19:26:19,388 INFO    Thread-17 :26780 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-03-09 19:26:19,388 INFO    Thread-17 :26780 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\Shivam Maurya\OneDrive\Desktop\IIT MADRAS\Deep Learning\assignment 1\CS6910-Deep_Learning_Assignment-1\wandb\run-20230309_192619-znk3ejhp\logs\debug.log
2023-03-09 19:26:19,388 INFO    Thread-17 :26780 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\Shivam Maurya\OneDrive\Desktop\IIT MADRAS\Deep Learning\assignment 1\CS6910-Deep_Learning_Assignment-1\wandb\run-20230309_192619-znk3ejhp\logs\debug-internal.log
2023-03-09 19:26:19,395 INFO    Thread-17 :26780 [wandb_init.py:init():532] calling init triggers
2023-03-09 19:26:19,395 INFO    Thread-17 :26780 [wandb_init.py:init():538] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 5, 'gamma': 0.03, 'hidden_layers': [32, 64, 128], 'learning_rate': 0.0006, 'optimizer': 'rmsprop', 'weight_decay': 0}
config: {}
2023-03-09 19:26:19,395 INFO    Thread-17 :26780 [wandb_init.py:init():554] re-initializing run, found existing run on stack: znk3ejhp
2023-03-09 19:26:19,395 INFO    Thread-17 :26780 [wandb_run.py:_finish():1854] finishing run cs22m083/CS6910_Assignment_1/znk3ejhp
2023-03-09 19:26:19,395 INFO    Thread-17 :26780 [jupyter.py:save_history():449] not saving jupyter history
2023-03-09 19:26:19,398 INFO    Thread-17 :26780 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-03-09 19:26:19,398 INFO    Thread-17 :26780 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2023-03-09 19:26:19,398 INFO    Thread-17 :26780 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-03-09 19:26:19,398 INFO    Thread-17 :26780 [wandb_run.py:_restore():2066] restore
2023-03-09 19:26:19,398 INFO    Thread-17 :26780 [wandb_run.py:_restore():2072] restore done
2023-03-09 19:26:24,115 INFO    Thread-17 :26780 [wandb_run.py:_footer_history_summary_info():3442] rendering history
2023-03-09 19:26:24,115 INFO    Thread-17 :26780 [wandb_run.py:_footer_history_summary_info():3474] rendering summary
2023-03-09 19:26:24,115 INFO    Thread-17 :26780 [wandb_run.py:_footer_sync_info():3398] logging synced files
2023-03-09 19:26:24,115 INFO    Thread-17 :26780 [wandb_init.py:init():588] starting backend
2023-03-09 19:26:24,115 INFO    Thread-17 :26780 [wandb_init.py:init():592] setting up manager
2023-03-09 19:26:24,131 INFO    Thread-17 :26780 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-03-09 19:26:24,138 INFO    Thread-17 :26780 [wandb_init.py:init():599] backend started and connected
2023-03-09 19:26:24,148 INFO    Thread-17 :26780 [wandb_run.py:_config_callback():1250] config_cb None None {'activation': 'tanh', 'batch_size': 16, 'epochs': 5, 'gamma': 0.03, 'hidden_layers': [32, 64, 128], 'learning_rate': 0.0006, 'optimizer': 'rmsprop', 'weight_decay': 0}
2023-03-09 19:26:24,148 INFO    Thread-17 :26780 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2023-03-09 19:26:24,148 INFO    Thread-17 :26780 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-03-09 19:26:24,148 INFO    Thread-17 :26780 [wandb_init.py:init():687] updated telemetry
2023-03-09 19:26:24,181 INFO    Thread-17 :26780 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-09 19:26:24,834 INFO    Thread-17 :26780 [wandb_run.py:_on_init():2134] communicating current version
2023-03-09 19:26:24,870 INFO    Thread-17 :26780 [wandb_run.py:_on_init():2143] got version response upgrade_message: "wandb version 0.13.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-03-09 19:26:24,870 INFO    Thread-17 :26780 [wandb_init.py:init():775] starting run threads in backend
2023-03-09 19:26:33,473 INFO    Thread-17 :26780 [wandb_run.py:_console_start():2114] atexit reg
2023-03-09 19:26:33,473 INFO    Thread-17 :26780 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-03-09 19:26:33,473 INFO    Thread-17 :26780 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-03-09 19:26:33,473 INFO    Thread-17 :26780 [wandb_run.py:_redirect():2059] Redirects installed.
2023-03-09 19:26:33,473 INFO    Thread-17 :26780 [wandb_init.py:init():817] run started, returning control to user process
2023-03-09 19:27:44,307 INFO    Thread-17 :26780 [wandb_run.py:_finish():1854] finishing run cs22m083/CS6910_Assignment_1/znk3ejhp
2023-03-09 19:30:46,084 ERROR   Thread-16 :26780 [internal_api.py:execute():245] 502 response executing GraphQL.
2023-03-09 19:30:46,084 ERROR   Thread-16 :26780 [internal_api.py:execute():246] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2023-03-09 20:44:37,932 ERROR   Thread-16 :26780 [internal_api.py:execute():245] 502 response executing GraphQL.
2023-03-09 20:44:37,932 ERROR   Thread-16 :26780 [internal_api.py:execute():246] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2023-03-09 20:46:28,530 ERROR   Thread-16 :26780 [internal_api.py:execute():245] 502 response executing GraphQL.
2023-03-09 20:46:28,530 ERROR   Thread-16 :26780 [internal_api.py:execute():246] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2023-03-09 20:48:20,190 ERROR   Thread-16 :26780 [internal_api.py:execute():245] 502 response executing GraphQL.
2023-03-09 20:48:20,190 ERROR   Thread-16 :26780 [internal_api.py:execute():246] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2023-03-09 20:51:55,344 ERROR   Thread-16 :26780 [internal_api.py:execute():245] 502 response executing GraphQL.
2023-03-09 20:51:55,344 ERROR   Thread-16 :26780 [internal_api.py:execute():246] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2023-03-09 22:22:38,651 ERROR   Thread-16 :26780 [internal_api.py:execute():245] 404 response executing GraphQL.
2023-03-09 22:22:38,651 ERROR   Thread-16 :26780 [internal_api.py:execute():246] {"errors":[{"message":"could not find agent 4wg4gzuv during agentHeartbeat","path":["agentHeartbeat"]}],"data":{"agentHeartbeat":null}}
